version: '3'
services:
  nginx:
    image: $NGINX_VERSION
    container_name: $NGINX_NAME
    restart: unless-stopped
    ports:
      - $NGINX_PORT:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nextcloud:/var/www/html
    networks:
      - nextcloud-net

  app:
    image: $NEXTCLOUD_VERSION
    container_name: $NEXTCLOUD_NAME
    restart: unless-stopped
    # expose:
    #   - '80'
    #   - '9000'
    environment:
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAINS: "localhost 127.0.0.1 172.18.0.1 nextcloud-nginx"
    volumes:
      - ./nextcloud:/var/www/html
    networks:
      - nextcloud-net

  cron:
    image: $NEXTCLOUD_VERSION
    container_name: $NEXTCLOUD_CRON
    restart: unless-stopped
    volumes:
      - ./nextcloud:/var/www/html:z
    environment:
      MYSQL_PASSWORD: $NEXTCLOUD_PASS
      MYSQL_DATABASE: $NEXTCLOUD_DB
      MYSQL_USER: $NEXTCLOUD_USER
      MYSQL_HOST: db
      REDIS_HOST: redis
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - nextcloud-net

  db:
    image: $MARIADB_VERSION
    container_name: $MARIADB_NAME
    restart: unless-stopped
    volumes:
      - ./mysql_data:/var/lib/mysql:z
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $NEXTCLOUD_DB
      MYSQL_USER: $NEXTCLOUD_USER
      MYSQL_PASSWORD: $NEXTCLOUD_PASS
    networks:
      - nextcloud-net

  onlyoffice-document-server:
    container_name: nextcloud-onlyoffice
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    # environment:
    #   - JWT_SECRET=secret
    expose:
      - '8090:80'
      - '443'
    volumes:
      - ./document_data:/var/www/onlyoffice/Data
      - ./document_log:/var/log/onlyoffice
    networks:
      - nextcloud-net

  redis:
    image: $REDIS_VERSION
    container_name: $REDIS_NAME
    restart: unless-stopped
    volumes:
      - ./redis:/data
    networks:
      - nextcloud-net

networks:
  nextcloud-net:
    driver: bridge
