version: '3'
services:
  nginx:
    image: $NGINX_VERSION
    container_name: $NGINX_NAME
    restart: unless-stopped
    ports:
      - $NGINX_PORT:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nextcloud:/var/www/html
    networks:
      network:
        ipv4_address: $NGINX_HOST

  app:
    image: $NEXTCLOUD_VERSION
    container_name: $NEXTCLOUD_NAME
    restart: unless-stopped
    environment:
      MYSQL_PASSWORD: $NEXTCLOUD_PASS
      MYSQL_DATABASE: $NEXTCLOUD_DB
      MYSQL_USER: $NEXTCLOUD_USER
      MYSQL_HOST: db
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAINS: $TRUSTED_DOMAINS
    volumes:
      - ./nextcloud:/var/www/html
    networks:
      network:
        ipv4_address: $NEXTCLOUD_HOST

  cron:
    image: $NEXTCLOUD_VERSION
    container_name: $NEXTCLOUD_CRON
    restart: unless-stopped
    volumes:
      - ./nextcloud:/var/www/html:z
    environment:
      MYSQL_PASSWORD: $NEXTCLOUD_PASS
      MYSQL_DATABASE: $NEXTCLOUD_DB
      MYSQL_USER: $NEXTCLOUD_USER
      MYSQL_HOST: db
      REDIS_HOST: redis
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      network:
        ipv4_address: $NEXTCRON_HOST

  db:
    image: $MARIADB_VERSION
    container_name: $MARIADB_NAME
    restart: unless-stopped
    volumes:
      - ./mysql_data:/var/lib/mysql:z
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $NEXTCLOUD_DB
      MYSQL_USER: $NEXTCLOUD_USER
      MYSQL_PASSWORD: $NEXTCLOUD_PASS
    networks:
      network:
        ipv4_address: $MARIADB_HOST

  redis:
    image: $REDIS_VERSION
    container_name: $REDIS_NAME
    restart: unless-stopped
    volumes:
      - ./redis:/data
    networks:
      network:
        ipv4_address: $REDIS_HOST

networks:
  network:
    driver: bridge
    name: $NETWORK_NAME
    ipam:
      config:
        - subnet: $NETWORK_ADDR
          gateway: $NETWORK_GATE
